# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(684, 628)
        font = QtGui.QFont()
        font.setPointSize(36)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.addWordBtn = QtWidgets.QPushButton(self.centralwidget)
        self.addWordBtn.setGeometry(QtCore.QRect(480, 50, 200, 75))
        self.addWordBtn.setMaximumSize(QtCore.QSize(425, 200))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.addWordBtn.setFont(font)
        self.addWordBtn.setObjectName("addWordBtn")
        self.replaceBtn = QtWidgets.QPushButton(self.centralwidget)
        self.replaceBtn.setGeometry(QtCore.QRect(410, 420, 260, 100))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.replaceBtn.setFont(font)
        self.replaceBtn.setObjectName("replaceBtn")
        self.replaceList = QtWidgets.QListWidget(self.centralwidget)
        self.replaceList.setGeometry(QtCore.QRect(10, 340, 400, 225))
        self.replaceList.setObjectName("replaceList")
        self.wordList = QtWidgets.QListWidget(self.centralwidget)
        self.wordList.setGeometry(QtCore.QRect(10, 10, 460, 150))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.wordList.setFont(font)
        self.wordList.setObjectName("wordList")
        self.searchText = QtWidgets.QLineEdit(self.centralwidget)
        self.searchText.setGeometry(QtCore.QRect(210, 180, 460, 65))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.searchText.setFont(font)
        self.searchText.setObjectName("searchText")
        self.replaceText = QtWidgets.QLineEdit(self.centralwidget)
        self.replaceText.setGeometry(QtCore.QRect(210, 260, 460, 65))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.replaceText.setFont(font)
        self.replaceText.setObjectName("replaceText")
        self.replaceTextAddBtn = QtWidgets.QPushButton(self.centralwidget)
        self.replaceTextAddBtn.setGeometry(QtCore.QRect(410, 340, 260, 75))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.replaceTextAddBtn.setFont(font)
        self.replaceTextAddBtn.setObjectName("replaceTextAddBtn")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(420, 530, 245, 20))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setEnabled(True)
        self.textBrowser.setGeometry(QtCore.QRect(10, 180, 200, 65))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(10, 260, 200, 65))
        self.textBrowser_2.setObjectName("textBrowser_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 684, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.addWordBtn.setText(_translate("MainWindow", "新增檔案"))
        self.replaceBtn.setText(_translate("MainWindow", "開始取代"))
        self.replaceTextAddBtn.setText(_translate("MainWindow", "新增取代文字"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:36pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">尋找文字：</p></body></html>"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:36pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">取代文字：</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
